### ISSUE TITLE
Built-in additional type filtering

### ISSUE THREAD

**Issue by AlexMeesters** [MPozek/Pickle#1]
Thank you for making this plugin.
There is one thing that Unity lacks that you might be able to solve with this plugin, that is being able to pick interfaces.

Right now you are able to fetch interfaces by doing:
[SerializeField] private MonoBehaviour myObjectThatHasInterface;

And dragging the Monobehaviour in, and casting it to the type you want it to be.
If this plugin is able to fetch all interfaces in the active scene of specified type, then that would make this plugin a lot more powerful.

**Comment by AlexMeesters** [comment]
In case anyone is wondering. It is already achievable with the custom filter by doing:

```csharp

[SerializeField, Pickle(LookupType = ObjectProviderType.Scene, FilterMethodName = nameof(CustomFilter))] 
private MonoBehaviour playerSkinLoader;
	
public bool CustomFilter(ObjectTypePair item) => item.Object is ILoadListener; // Check for interface ILoadListener

```

**Comment by MPozek** [comment]
Thanks for the feature request. I see how this could be useful as a built-in solution.
I'll review your PR #2, though I might reject it and integrate custom typing more tightly into the plugin. The core idea is the same.
If I can, I'll keep your attribute field name so that the update remains compatible with your syntax.

**Comment by AlexMeesters** [comment]
Feel free to change it how you envision it, no need to keep things the because of how I'm using it.
I might just refactor some of my code to match your methodology afterwards.

**Comment by MPozek** [comment]
Version 1.2.0 addresses this along with some other usability changes.
In the end the implementation wasn't so different from yours.
Thanks for bringing this use-case to my attention!
